# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    increment_build_number
    get_certificates
    gym(scheme: "Gebruikr App", export_xcargs: "-allowProvisioningUpdates")
    upload_to_testflight
    
    notification(subtitle: "Beta klaar", message: "Beta is geupload naar Apple")
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

end

